alias ga="git add -a"
alias gcm="git commit -m"
alias gcam="git commit -am"
alias glog="git log --graph --pretty=format:'%Cred%h%Creset %an: %s - %Creset %C(yellow)%d%Creset %Cgreen(%cr)%Creset' --abbrev-commit --date=relative"
alias gp="git pushre"